[CLIENT-8061] Catch `gUM` errors in FF.
twilio/rtc-diagnostics pull request #60
Opened 2020-10-28 18:34 UTC by mhuynh5757

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [CLIENT-8061](https://issues.corp.twilio.com/browse/CLIENT-8061)

### Description

This PR introduces error handling for FF specific `gUM` errors.

## Burndown

### Before review
* [x] Updated CHANGELOG.md if necessary
* [x] Added unit tests if necessary
* [x] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [x] Included screenshot as PR comment (if needed)
* [x] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

2020-10-28 19:13 UTC, charliesantos approved these changes
+1 for me. After getting +1 from Ryan, please don't merge yet because we have a GA release soon. I don't want to block that.

2020-11-03 22:38 UTC, ryan-rowland requested changes

2020-11-03 22:38 UTC, ryan-rowland commented on lib/AudioInputTest.ts
> +          'An `Error` has occurred.',
What's with `Error`? I think we can just say:
> An error has occurred.

2020-11-04 19:42 UTC, ryan-rowland approved these changes

2020-11-04 19:42 UTC, merged